[mov-cli]
version = 1
player = "vlc"
debug = false
# parser = "lxml"
editor = "nvim"

[mov-cli.ui]
fzf = true

[mov-cli.scrapers]
default = "test.test"

[mov-cli.plugins] # E.g: namespace = "package-name"
test = "mov-cli-test"
films = "mov-cli-films"
anime = "mov-cli-anime"

# [mov-cli.http] # Don't mess with it if you don't know what you are doing!
# headers = { User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0" }

# [mov-cli.downloads]
# save_path = "~/Downloads"
